import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { BookingProvider } from "./components/booking-provider";
import { MobileNav } from "./components/mobile-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <BookingProvider>
          {children}
          <MobileNav />
        </BookingProvider>
        <Script
          src="https://cdn.userway.org/widget.js"
          data-account="2wHGR7XGAC"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
